// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIS6T-Xjnz9GTKmtB1zLRwL8IA_RLXJFw',
    appId: '1:110117611306:web:0267cdf8e5d2d26a99a053',
    messagingSenderId: '110117611306',
    projectId: 'cutflow-1925a',
    authDomain: 'cutflow-1925a.firebaseapp.com',
    storageBucket: 'cutflow-1925a.appspot.com',
    measurementId: 'G-5HYHMT4KR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdsz4XDLlQSzqLcH8RqBCopXx_KvJQWfs',
    appId: '1:110117611306:android:81fd0c9d766eb69799a053',
    messagingSenderId: '110117611306',
    projectId: 'cutflow-1925a',
    storageBucket: 'cutflow-1925a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWHEmyv-8YJEfnThO8QMPB6tuOhcRR2dk',
    appId: '1:110117611306:ios:c55d629f2c027ae099a053',
    messagingSenderId: '110117611306',
    projectId: 'cutflow-1925a',
    storageBucket: 'cutflow-1925a.appspot.com',
    iosBundleId: 'com.example.cutflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWHEmyv-8YJEfnThO8QMPB6tuOhcRR2dk',
    appId: '1:110117611306:ios:c55d629f2c027ae099a053',
    messagingSenderId: '110117611306',
    projectId: 'cutflow-1925a',
    storageBucket: 'cutflow-1925a.appspot.com',
    iosBundleId: 'com.example.cutflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIS6T-Xjnz9GTKmtB1zLRwL8IA_RLXJFw',
    appId: '1:110117611306:web:7bec32568cf8446999a053',
    messagingSenderId: '110117611306',
    projectId: 'cutflow-1925a',
    authDomain: 'cutflow-1925a.firebaseapp.com',
    storageBucket: 'cutflow-1925a.appspot.com',
    measurementId: 'G-0EQJY0E7SZ',
  );
}
